name: Build AmneziaWG for AXT1800 Slate

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

env:
  OWR_BRANCH: openwrt-23.05
  GL_VERSION: '4.8.0'
  GL_VERMAGIC: any

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # 1) Checkout this repo (so config_4.8.0.buildinfo is present)
      - name: Checkout main repo
        uses: actions/checkout@v4

      # 2) Checkout the AmneziaWG overlay (with the package definitions)
      - name: Checkout AmneziaWG overlay
        uses: actions/checkout@v4
        with:
          repository: SaltyNewfie/amneziawg-openwrt
          path: amneziawg-openwrt
          fetch-depth: 0

      # 3) Clone the OpenWrt 23.05 snapshot
      - name: Clone OpenWrt snapshot
        run: |
          git clone --depth 1 --branch "${OWR_BRANCH}" \
            https://github.com/openwrt/openwrt.git openwrt

      # 4) Copy in your 533-line .config
      - name: Apply GL.iNet buildinfo (.config)
        run: |
          cp config_${{ env.GL_VERSION }}.buildinfo openwrt/.config

      # 5) **Correct** overlay: copy from overlay/package, not overlay/openwrt
      - name: Overlay AmneziaWG packages
        run: |
          cp -r amneziawg-openwrt/package/amneziawg-* openwrt/package/

      # 6) Prepare feeds
      - name: Prepare feeds
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      # 7) Build the three AmneziaWG packages
      - name: Build AmneziaWG packages
        run: |
          cd openwrt
          make package/amneziawg-tools/compile V=s -j$(nproc)
          make package/luci-proto-amneziawg/compile V=s -j$(nproc)
          make package/kmod-amneziawg/compile V=s -j$(nproc)

      # 8) Collect the .ipk artifacts
      - name: Collect artifacts
        run: |
          cd openwrt
          mkdir -p awg
          cp bin/packages/aarch64_cortex-a53/base/amneziawg-tools_*.ipk awg/
          cp bin/packages/aarch64_cortex-a53/base/luci-proto-amneziawg_*.ipk awg/
          cp bin/targets/ipq806x/generic/packages/kmod-amneziawg_*.ipk awg/

      # 9) Publish a GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: "AmneziaWG v${{ env.GL_VERSION }} (AXT1800)"
          tag_name: "${{ github.ref_name }}"
          files: openwrt/awg/*.ipk
