name: Build AmneziaWG for AXT1800 Slate

on:
  workflow_dispatch:

permissions:
  contents: write

env:
  OWR_BRANCH: openwrt-23.05
  GL_VERSION: '4.8.0'
  GL_VERMAGIC: any

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # 1) Grab the package definitions overlay
      - name: Checkout AmneziaWG overlay
        uses: actions/checkout@v4
        with:
          repository: SaltyNewfie/amneziawg-openwrt
          path: amneziawg-openwrt
          fetch-depth: 0

      # 2) Clone OpenWrt itself
      - name: Clone OpenWrt snapshot
        run: |
          git clone --depth 1 --branch "${OWR_BRANCH}" \
            https://github.com/openwrt/openwrt.git openwrt

      # 3) Copy your full 4.8.0 .config into place
      - name: Apply GL.iNet buildinfo (.config)
        run: |
          cp config_${{ env.GL_VERSION }}.buildinfo openwrt/.config

      # 4) Overlay in the AmneziaWG packages
      - name: Copy AmneziaWG package overlay
        run: |
          cp -r amneziawg-openwrt/package/amneziawg-* openwrt/package/

      # 5) Prepare feeds (only core feeds, overlays are already in openwrt/package/)
      - name: Prepare feeds
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      # 6) Compile your three packages
      - name: Build AmneziaWG packages
        run: |
          cd openwrt
          make package/amneziawg-tools/compile V=s -j$(nproc)
          make package/luci-proto-amneziawg/compile V=s -j$(nproc)
          make package/kmod-amneziawg/compile V=s -j$(nproc)

      # 7) Collect the resulting .ipk files
      - name: Collect artifacts
        run: |
          cd openwrt
          mkdir -p awg
          cp bin/packages/aarch64_cortex-a53/base/amneziawg-tools_*.ipk awg/
          cp bin/packages/aarch64_cortex-a53/base/luci-proto-amneziawg_*.ipk awg/
          cp bin/targets/ipq806x/generic/packages/kmod-amneziawg_*.ipk awg/

      # 8) Push a GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: "AmneziaWG v${{ env.GL_VERSION }} (ATX1800)"
          tag_name: "ATX1800_v${{ env.GL_VERSION }}"
          files: openwrt/awg/*.ipk
