name: Build AmneziaWG for ATX1800 Slate

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

env:
  OWR_BRANCH: openwrt-24.10
  OWR_COMMIT: ea17e958b9
  GL_VERSION: 4.7.5
  GL_VERMAGIC: any

jobs:
  build:
    name: Build AXT1800 Packages
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout AmneziaWG repo
        uses: actions/checkout@v4

      - name: Clone OpenWrt
        run: |
          # clone just the branch first
          git clone --depth 1 --branch "${OWR_BRANCH}" \
            https://github.com/openwrt/openwrt.git openwrt
          cd openwrt
          # fetch & checkout the exact commit
          git fetch --depth 1 origin "${OWR_COMMIT}"
          git checkout "${OWR_COMMIT}"

      - name: Prepare Feeds
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Build Tools & Packages
        run: |
          cd openwrt
          make package/amneziawg-tools/{download,prepare,compile} V=s -j$(nproc)
          make package/luci-proto-amneziawg/compile V=s -j$(nproc)
          make package/kmod-amneziawg/compile V=s -j$(nproc)

      - name: Collect Artifacts
        run: |
          cd openwrt
          mkdir -p awg
          cp bin/packages/aarch64_cortex-a53/base/amneziawg-tools_*.ipk awg/
          cp bin/packages/aarch64_cortex-a53/base/luci-proto-amneziawg_*.ipk awg/
          cp bin/targets/ipq806x/generic/packages/kmod-amneziawg_*.ipk awg/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: "AmneziaWG v${{ env.GL_VERSION }} (AXT1800)"
          tag_name: "ATX1800_v${{ env.GL_VERSION }}"
          files: openwrt/awg/*.ipk
